### ISSUE TITLE
An error occurs when changing the scene.

### ISSUE THREAD

**Issue by HidehikoKondo** [googlevr/gvr-instant-preview#1]
I had problems when I tried using instant preview.
While instant preview is running, an error occurs in the next scene after the scene changes.

---
Unity Version: 5.6.1f1
GVR Unity SDK Version: 1.50.0
Instant Preview Version: 1.0.0.0

---
Error:
（FindObjectsOfType can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
UnityEngine.Object:FindObjectsOfType(Type)
Gvr.Internal.EmulatorConfig:get_Instance() (at Assets/GoogleVR/Scripts/Controller/Internal/Emulator/EmulatorConfig.cs:23)
Gvr.Internal.EmulatorClientSocket:phoneConnect() (at Assets/GoogleVR/Scripts/Controller/Internal/Emulator/EmulatorClientSocket.cs:82)
Gvr.Internal.EmulatorClientSocket:phoneEventSocketLoop() (at Assets/GoogleVR/Scripts/Controller/Internal/Emulator/EmulatorClientSocket.cs:63)
）

![instantpreviewerror](https://cloud.githubusercontent.com/assets/3691510/26244520/f14fbdf2-3cca-11e7-895f-86418631edda.png)

**Comment by gstanlo** [comment]
Hi,

If you open EmulatorConfig.cs and add the following function to the EmulatorConfig class, does that suppress the error?

```
    void Awake () {
      DontDestroyOnLoad(this);
    }

```

**Comment by HidehikoKondo** [comment]
That error was suppressed.
Thank you.
