### ISSUE TITLE
Pressing Play in the Unity Editor does nothing

### ISSUE THREAD

**Issue by ylluminarious** [googlevr/gvr-instant-preview#10]
When I press Play in the Unity Editor, nothing happens. Nothing on my phone or in the editor itself.

Here is some info about my setup, as laid out by [the troubleshooting guide](https://developers.google.com/vr/tools/instant-preview#troubleshooting_in_unity):

---
- [x] Check for any Instant Preview errors in the Unity Console.
    - I have no errors at all in my Unity console.
- [x] If the controller is not working, ensure that the Instant Preview plugin was imported **after** the GVR Unity plugin.
    - [x] Instant Preview works by **overwriting** some files in the GVR Unity SDK. EmulatorControllerProvider.cs should have a reference to the `InstantPreviewControllerProvider` inside it if it is setup correctly.
        - My EmulatorControllerProvider.cs file does indeed contain references to `InstantPreviewControllerProvider`.
- [x] Your build platform is set to Android.
    - Yes. I also have the following build settings:
        - `Texture Compression` set to "Don't override"
        - `Build System` set to "Internal (Default)"
        - `Export Project` set to off
        - `Development Build` set to on
        - `Autoconnect Profiler` set to off
        - `Script Debugging` set to on
- [x] You have imported both the gvr-unity-sdk and InstantPreview .unitypackage to your project.
    - I have v1.70.0 of Google VR SDK and v1.1.0 of Instant Preview.
- [x] You have added the `GvrInstantPreviewMain` prefab to your scene.
    - Yes. It is also enabled.
- [ ] Confirm that when you press Play in Unity, the Console displays both "GVR Unity SDK Version: 1.xx" and "Instant Preview Version: 1.0.0.x" (where x is replaced by a version number).
    - **This does not happen.** I receive **no** messages when I press the Play button in Unity. **_This may have something to do with what is causing my problem to occur._**

**Comment by tomgoogle** [comment]
Which package did you import? There's a matching 1.70 instant preview package specifically for 1.70 Google VR SDK.

If nothing is happening in your editor (even playing in editor) then it sounds like there might be a compile error somewhere. 

-Tom

**Comment by ylluminarious** [comment]
@tomgoogle Thanks for the quick reply. I just uninstalled my old Instant Preview version (1.1.0) via `git revert`  and I downloaded and installed the 1.7.0 version. Unfortunately I am still experiencing the same problems. Do you know how I could track down a compile error, as you mentioned, given that there are no errors in my Unity console?

**Comment by tomgoogle** [comment]
Hmm, it should be in your log window if you have compile errors.

When you press Play, what happens? If you have compile errors, it should flash with "You must fix your compile errors" (or similar) comment. More details here: http://answers.unity3d.com/questions/33436/how-do-i-fix-all-compiler-errors-so-i-can-enter-pl.html

If your application actually plays (but without Instant Preview), then the problem lies elsewhere. Does your application actually play in the game window in editor?

**Comment by ylluminarious** [comment]
@tomgoogle I have no compile errors in my log window nor any other errors, as I stated in my first post. I apologize as I have been hitherto unclear: it's actually not that **nothing** happens when I press Play. The game plays as usual, but there are no visible effects from Instant Preview. So the answer to your last question is yes, but Instant Preview is seemingly doing nothing.

**Comment by tomgoogle** [comment]
Got it :)

If you look in Assets/InstantPreview/InstantPreview.cs in the Start() function, the first thing we do is print the version string. If you aren't seeing it, there must be something in your setup that is stopping this. 

It could either be the include guards in InstantPreview.cs removing this code (see #if UNITY_ANDROID && UNITY_HAS_GOOGLEVR && UNITY_EDITOR) or your prefab not being enabled for some reason. Can you check if these defines are set, by adding some code that obviously doesn't compile inside them?

-Tom

**Comment by ylluminarious** [comment]
@tomgoogle Thanks a lot for the info. So I added some random gibberish directly beneath the `#if` preprocessor check on line 85 and I then got compile errors in my log window. That's rather odd, since it means that Unity has defined all those directives but it's not making it to the `Start` function for some reason.

**Comment by tomgoogle** [comment]
If you have the ability to debug, place a breakpoint at the top of Start (or add your own logging right at the top). It really sounds like the object isn't enabled...somehow. Double check that when you run, the GvrInstantPreviewMain object is in the DontDestroyOnLoad group, and enabled.

**Comment by ylluminarious** [comment]
@tomgoogle I added the following statement at the very beginning of `Start`:
```
void Start() {
  Debug.LogError("testing testing");
  ...
```
And I saw it printed in my console:
```
testing testing
UnityEngine.Debug:LogError(Object)
Gvr.Internal.InstantPreview:Start() (at Assets/InstantPreview/InstantPreview.cs:156)
```
I also double checked the prefab after running the game by pressing Play:
![pic](https://user-images.githubusercontent.com/4912973/30302533-9ac212c2-972f-11e7-8684-33626f7fa42e.png)

That is what it looks like in the `DontDestroyOnLoad` group which is apparently created at runtime.

**Comment by tomgoogle** [comment]
Alright, that's strange then. Is it definitely never printing the instant preview version? It must be running into an exception prior to that, in that case. 

Also check to see if Instant Preview actually was deployed to your phone. You can see the code in InstantPreview.cs that auto-installs the APK and runs it if it's already there. Make sure your phone is connected via USB (and calling "adb devices" from the command line returns a valid device).

**Comment by ylluminarious** [comment]
@tomgoogle It is definitely not printing the Instant Preview version. I have verified that Instant Preview is in fact installed to my phone. My phone is connected via USB and registers as a valid device under `adb devices`.

**Comment by gstanlo** [comment]
Do you have multiple phones connected via USB? There's no UI to switch between connected devices, so many of the commands sent to adb won't work as expected. 

If you launch the Instant Preview app on your phone, does it say that it is connected? If the app has been deployed already, you might be able to use the WiFi mode instead of USB. USB can have unstable behavior depending on the connection.

Unity might be leaving an adb connection open, and the app is connecting to the wrong Unity process accidentally. If this is the case, a heavy handed solution is to close Unity, run "adb kill-server", and reopen your Unity project.

**Comment by ylluminarious** [comment]
@gstanlo 

> Do you have multiple phones connected via USB? There's no UI to switch between connected devices, so many of the commands sent to adb won't work as expected.

I do not have multiple devices connected via USB.

> If you launch the Instant Preview app on your phone, does it say that it is connected? If the app has been deployed already, you might be able to use the WiFi mode instead of USB. USB can have unstable behavior depending on the connection.

The Instant Preview app on my phone said before that it was connected to the editor. Yet, it would not have any effect on the editor's player, as I explained. Now, though, the phone is saying that it is not connected to the editor. Even though I started the app by pressing Play in Unity. This is likely due to some things that I tried, as per your suggestions. For example, I first tried restarting Unity and the `adb` daemon. That seemed to have corrupted the `adb` daemon, which would not allow me to even kill it. So I had no recourse, other than to reboot my system. And so now, it appears that my phone is refusing to connect to Unity. I've even tried plugging the phone into different ports, which has yielded no solution. So your assertion about USB being finicky is correct.

I am now trying to get the connection going over Wifi, but I am having trouble in getting this to work. [The docs say:](https://developers.google.com/vr/tools/instant-preview)

> To connect via WiFi, Instant Preview uses multicast address 239.170.165.207 on port 49838 to find host computers, so your network must allow this.

I am not sure how to get my phone to find my workstation via this address. For one thing, this address uses a totally different subnet than my office's LAN. Do you have any advice on this issue?

**Comment by ylluminate** [comment]
Well this is a strange thing indeed to me.  It seems as though you are dealing with a subnet issue ultimately.  Why would Google have chosen to place the device on another subnet vs allowing it to run on the present subnet of the wireless to which it is connected?  If you were operating on 192.168.0.x, for example, the device should be broadcasting upon this 255.255.255.0 subnet.  Is there no way to change the device's software configuration to operate as such?  If not, I cannot see how it's isolated to this IP only...

**Comment by ylluminarious** [comment]
@ylluminate Yes, you are articulating exactly what I am trying to say that my problem is. Alas, I see no options in the Instant Preview app on my phone to change the configuration in this regard.

**Comment by ylluminate** [comment]
I have to believe that we're missing something with regards to how multicast is supposed to function and perhaps something on our network is precluding its functionality... I've pushed up a question [here](https://serverfault.com/questions/873391/what-does-having-a-network-that-would-allow-a-multicast-address-to-find-host-com) about it to see if we can get some additional insight as I'm shooting blanks right now.

**Comment by gstanlo** [comment]
Multicasting over a different subnet will require some sort of network configuration that I'm not personally familiar with. The expectation was that the phone and computer would be on the same subnet. As alternative, you can connect your computer to your phone as a WiFi hotspot (make sure to turn off data usage) if you have a wireless adapter on your computer.

> The Instant Preview app on my phone said before that it was connected to the editor. Yet, it would not have any effect on the editor's player, as I explained. Now, though, the phone is saying that it is not connected to the editor. Even though I started the app by pressing Play in Unity. This is likely due to some things that I tried, as per your suggestions. For example, I first tried restarting Unity and the adb daemon. That seemed to have corrupted the adb daemon, which would not allow me to even kill it. So I had no recourse, other than to reboot my system. And so now, it appears that my phone is refusing to connect to Unity. I've even tried plugging the phone into different ports, which has yielded no solution. So your assertion about USB being finicky is correct.

If the app says that it is connected to the editor, it's possible that it's connected to an incorrect Unity instance. Instant Preview tries to listen on port 49838 when it's loaded, and if the port is already in use, it unfortunately won't be able to make any connections. 

If the app says it's connected and no unity instances are open, try running `netstat -ano | findstr 49838` on Windows or `lsof -i tcp:49838` on OSX to find whether something is incorrectly listening on the port.

@ylluminarious After restarting, were you able to connect via USB?

**Comment by ylluminate** [comment]
So yes, @tomgoogle @gstanlo I ended up testing multicasting via [this procedure](https://helpdesk.kaseya.com/hc/en-gb/articles/229021468-How-to-test-if-Multicast-is-working-on-your-network).  Eg, sending with: 
`udp-sender -full-duplex --min-clients 1 --max-wait 480 --nokbd --mcast-all-addr 239.170.165.207 --portbase 49838 --ttl 1 --file test.iso`

And receiving with:
`udp-sender -full-duplex --min-clients 1 --max-wait 480 --nokbd --mcast-all-addr 239.170.165.207 --portbase 49838 --ttl 1 --file test.iso`

Initially I did find a problem that we're having with the wireless router that's bridging the network.  Apparently it was a dual pronged issue that required having both IGMP Proxy on and turning off the SPI firewall.  After Doing this we were able to send and receive test packets briefly and then it stopped again.  Now I've updated the wireless access point's firmware and going through some additional steps.  No luck yet, but the packets send and receive fine everywhere on the network except the wireless and so I suspect that's the real issue here.

**Comment by ylluminarious** [comment]
@gstanlo 
> [...] As alternative, you can connect your computer to your phone as a WiFi hotspot (make sure to turn off data usage) if you have a wireless adapter on your computer.

Unfortunately, I do not currently have a wireless adapter on my computer but I can try to get one.

> If the app says that it is connected to the editor, it's possible that it's connected to an incorrect Unity instance. Instant Preview tries to listen on port 49838 when it's loaded, and if the port is already in use, it unfortunately won't be able to make any connections.

Unfortunately, I do not currently have a wireless adapter on my computer but I can try to get one.

Ok, so at first I thought that this wasn't a problem but I seem to be wrong.

So, I noticed a couple of things when I started investigating this. First off, I saw that whenever I start Unity, it spawns an `adb` server process. This happens regardless of whether there is a already another server running. I assume that this server which Unity spawns is the one which attached to Unity. Thus, I also assume that is the server that actually communicates with my phone.

Yet, I also noticed that this server is always listening on port 5037, which is the wrong port. So, I used the [EnvPane](https://github.com/hschmidt/EnvPane) application to set `ANDROID_ADB_SERVER_PORT` to 49838 and I restarted Unity. After that, I checked Unity's environment via `htop` and I saw this line indicating that the variable was set:
```
ANDROID_ADB_SERVER_PORT=49838
```
However, I noticed that there was no `adb` process spawned by Unity this time. Finally, when I pressed Play, I got this error in the log window:
```
error: protocol fault (status 00 00 0c 04?!)
UnityEngine.Debug:LogError(Object)
Gvr.Internal.<Start>c__AnonStorey1:<>m__0() (at Assets/InstantPreview/InstantPreview.cs:196)
```
I tried rebooting to see if it would remove this error, but no such luck. So it seems that I can't get Unity to run the `adb` server on port 49838, which is obviously another problem in and of itself.

**Comment by ylluminarious** [comment]
@tomgoogle @gstanlo 
Also, @ylluminate is one of my colleagues in my office so that's why he's commenting here as well :)

**Comment by ylluminate** [comment]
So this was a bit hairy and the existing firmware on the router apparently is just terrible with multicast.  I went ahead and "upgraded" to DD-WRT for the device and now things are sane.  We're getting consistent multicast results for `239.170.165.207:49838` at this point and so we'll see where this leads us.

**Comment by ylluminate** [comment]
Still no luck on our end here getting this to work @tomgoogle & @gstanlo. Attempted to call Google Support and the gal told us they'd get us over to developer support after fiddling with her for about 45 minutes to an hour.  She fell through in her assurances and never sent us the appropriate phone number as promised.  There does seem to be something truly wrong here in that it does indeed appear that even with the USB connection it talks to the phone since when @ylluminarious hits play the app is triggered and gives the option of whether to preview or to use the Daydream controller.  It has lead us both to believe that we've been chasing our tails here with regards to the above exercises.  It really seems that we need more logging information and after tailing both the `adb` and Unity editor logs, we're still not getting any real details to anything, even when the initial connection is made...

**Comment by gstanlo** [comment]
> So, I noticed a couple of things when I started investigating this. First off, I saw that whenever I start Unity, it spawns an adb server process. This happens regardless of whether there is a already another server running. I assume that this server which Unity spawns is the one which attached to Unity. Thus, I also assume that is the server that actually communicates with my phone.

> Yet, I also noticed that this server is always listening on port 5037, which is the wrong port. So, I used the EnvPane application to set ANDROID_ADB_SERVER_PORT to 49838 and I restarted Unity. After that, I checked Unity's environment via htop and I saw this line indicating that the variable was set:

5037 is the default ADB port. That's fine to leave like that -- 49838 is what Instant Preview uses, so they both shouldn't be the same port. You can use adb over wifi and it would need 5037 to be open (or another port you choose). 

What's the state that your device ends up in when you hit Play? The expected behavior is that it starts the app, enters a connected state, and begins streaming in VR unless otherwise specified. Does it say it's connected?

Also, I can take a look at your adb logs and might be able to find something if you send them to stanlo@google.com.

**Comment by ylluminarious** [comment]
@gstanlo 

> 5037 is the default ADB port. That's fine to leave like that -- 49838 is what Instant Preview uses, so they both shouldn't be the same port. You can use adb over wifi and it would need 5037 to be open (or another port you choose).

Ok, thanks for the clarification. I presumed that port 49838 was supposed to be used by `adb` and that `adb` is what facilitated communication for Instant Preview.

> What's the state that your device ends up in when you hit Play? The expected behavior is that it starts the app, enters a connected state, and begins streaming in VR unless otherwise specified. Does it say it's connected?

Since I can't seem to explain this properly in words, [here's a dual screencast](https://youtu.be/ubDzkKehZCE) (with my phone and my computer) showing the whole thing in action.

> Also, I can take a look at your adb logs and might be able to find something if you send them to stanlo@google.com.

Thanks, will do.

**Comment by ylluminarious** [comment]
@gstanlo I finally managed to test this out on another machine of mine and I am still having the same issues. I sent you more info about it in an email.

**Comment by ylluminarious** [comment]
@gstanlo @tomgoogle I can't believe believe I hadn't thought to try this already, but oh well. I just tried using Instant Preview with the GVRDemo scene that comes with the GoogleVR SDK, and *it worked.* I suppose that means that there is something specific in my game scene that is causing Instant Preview to not take effect. Does anyone have any idea as to what could be causing that?

**Comment by ylluminarious** [comment]
@gstanlo @tomgoogle Well, my excitement was short-lived. Earlier today I had to update my phone due to some issues with the battery not working correctly. Thereafter, Instant Preview is no longer working, even on the demo scene.

My Android version is 7.1.1, Kernel 3.18.31, Build Number A2017UV1.1.0B32

**Comment by ylluminarious** [comment]
@tomgoogle @gstanlo 

So eventually, by trying techniques from various tutorials about Daydream and Unity, I determined the cause of this problem:

_**I forgot to add a `MainCamera` tag to my scene's main camera**_

According to an email that @gstanlo sent me, this would cause my issue because:

> We use that tag to grab the scene render and then stream it, so if there's no main camera it won't work.

So it all makes sense now and I can use Instant Preview just fine, after adding the `MainCamera` tag to my scene's camera.

However, I *strongly* suggest putting a notice for this requirement in the Instant Preview documentation. That would help others like myself to avoid this terribly confusing problem.

Feel free to close this ticket at your leisure.
