### ISSUE TITLE
Adb Not Detected.  Please add adb to your path and restart the Unity editor.

### ISSUE THREAD

**Issue by Enumio** [googlevr/gvr-instant-preview#5]
Adb Not Detected.  Please add adb to your path and restart the Unity editor.
UnityEngine.Debug:LogError(Object)
InstantPreviewHelper:Awake() (at Assets/InstantPreview/InstantPreviewHelper.cs:35)
UnityEditor.DockArea:OnGUI()

Unity 5.6.1 f1
Nexus 6P
GVR 1.50.0
InstantPreview 1.0.0.11

I don't understand this. My Android SDK and JDK are set up properly. I have enabled USB debugging on my phone.

Let me know if you need more info.

**Comment by vinhui** [comment]
You have not added adb to PATH
http://www.howtodroid.com/2014/02/how-to-add-adb-command-prompt-windows.html

**Comment by Enumio** [comment]
Thank you very much!!
